variables:
  PROJECT_NAME: "MLOPS-106"

stages: 
- train
- test 
- deploy

train:
  stage: train
  script:
    - echo "Train model for ${PROJECT_NAME}"
    - echo "Project Repository - ${CI_PROJECT_URL}"
    - ls -la 
    - mkdir models
    - cd models  
    - touch model.txt && echo "best model, F1=0.9" >> model.txt
    - ls -la 
    - echo "Model train complete"
  artifacts:
        paths:
            - models/

build:
  stage: test
  needs:
    - train
  script:
    - more models/model.txt
    - echo "Build Docker image or Virtual Environment"

test:
  stage: test
  needs:
    - build
  script:
    - echo "Test model"
    - mkdir reports
    - cd reports 
    - touch report.txt
    - echo "F1:0.9" >> report.txt
    - echo "Model test compete"
  artifacts:
    paths:
      - reports/report.txt

deploy:
  stage: deploy
  script:
    
    - echo "Model deployed to Server"
    - echo "Run scoring"
    - touch predictions.txt
    - echo "course_end_probability:0.995" >> predictions.txt
    - echo "Scorirng has completed"
  artifacts:
    paths:
      - predictions.txt
