stages:
  - build
  - test
  - deploy

build_model:
  stage: build
  script:
    - echo "This job builds something."

test_model:
  stage: test
  script:
    - echo "This job tests something. It will only run when all jobs in the"
    - echo "Test stage are complete."

deploy_model:
  stage: deploy
  script:
    - echo "This job deploys something. It will only run when all jobs in the"
    - echo "Deploy stage complete."
