# Basic GitLab CI example for beginners
# This shows the fundamental concepts of CI/CD pipelines

stages:
  - build
  - train
  - deploy

build_artifacts:
  stage: build
  script:
    - echo "This job builds something (Docker, packages...)"

test_code:
  stage: build
  script:
    - echo "This job tests something built by the build_artifacts job"
    - echo "Test job is complete"

train_model:
  stage: train
  script:
    - echo "This job trains a new model"
    - echo "Model train is complete"

deploy_model:
  stage: deploy
  script:
    - echo "This job deploys a model"
    - echo "Model deploy is complete"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual  # Require manual approval for deployment
