# Example from examples/1-get-started.yml

stages:
  - build
  - train
  - deploy

build_artifacts:
  stage: build
  script:
    - echo "This job builds something (Docker, packages...)"

test_code:
  stage: build
  script:
    - echo "This job tests something built by the build_artifacts job"
    - echo "Test job is complete"

train_model:
  stage: train
  script:
    - echo "This job trains a new model"
    - echo "Model train is complete"

deploy_model:
  stage: deploy
  script:
    - echo "This job deploys a model"
    - echo "Model deploy is complete"
