# Basic GitHub Actions workflow for beginners (with modern uv dependency management)
# This shows the fundamental concepts of CI/CD pipelines
# Equivalent to gitlab-examples/1-get-started.yml

name: 1-get-started

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'

jobs:
  # Build stage
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies with uv..."
          uv pip install --system --requirement pyproject.toml
      
      - name: Build step
        run: echo "This job builds something (Docker, packages...)"

  test_code:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: Install dependencies with dev tools
        run: uv pip install --system --requirement pyproject.toml --extra dev
      
      - name: Test step
        run: |
          echo "This job tests something built by the build_artifacts job"
          echo "Test job is complete"

  # Train stage
  train_model:
    name: Train Model
    runs-on: ubuntu-latest
    needs: test_code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      
      - name: Install dependencies
        run: uv pip install --system --requirement pyproject.toml
      
      - name: Train step
        run: |
          echo "This job trains a new model"
          echo "Model train is complete"

  # Deploy stage
  deploy_model:
    name: Deploy Model
    runs-on: ubuntu-latest
    needs: train_model
    if: github.ref == 'refs/heads/main'
    environment: production  # Requires manual approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy step
        run: |
          echo "This job deploys a model"
          echo "Model deploy is complete" 
