# Simple GitHub Actions workflow - equivalent to .gitlab-ci.yml simplicity
# This is the simplest possible version for learning

name: github-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "This job builds something (Docker, packages...)"

  test_code:
    runs-on: ubuntu-latest
    needs: build_artifacts
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "This job tests something built by the build_artifacts job"
          echo "Test job is complete"

  train_model:
    runs-on: ubuntu-latest
    needs: test_code
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "This job trains a new model"
          echo "Model train is complete"

  deploy_model:
    runs-on: ubuntu-latest
    needs: train_model
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "This job deploys a model"
          echo "Model deploy is complete" 
